openapi: 3.0.3
info:
  title: Tool
  description: |-
    This is a tool
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
tags:
  - name: ip-range
    description: AWS ip-ranges
    externalDocs:
      description: Find out more
      url: https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html
paths:
  /ip-range/findByRegion:
    get:
      tags:
        - ip-range
      summary: Finds ip-ranges by region
      operationId: findIpRangesByRegion
      parameters:
        - name: region
          in: query
          description: Region value that needs to be considered for filtering
          required: true
          schema:
            type: string
            enum:
              - EU
              - US
              - AP
              - CN
              - SA
              - AF
              - CA
              - ALL          
      responses:
        '200':
           description: successful operation
